#!/usr/bin/env python3
"""Generate a C byte-array source from a file.

Usage:
    gen_embed.py input.lua output.c symbol_prefix

Writes:
    const char symbol_prefix[] = { ... bytes ... , 0 };
    const size_t symbol_prefix_len = N;  /* N = input byte length, excluding NUL */
"""

from __future__ import annotations

import os
import sys

BYTES_PER_LINE = 12


def format_byte(value: int) -> str:
    # Printable ASCII except '\\' and '\'' -- no C escaping required.
    if 32 <= value <= 126 and value not in (39, 92):
        return f"'{chr(value)}'"
    return f"'\\x{value:02x}'"


def generate(data: bytes, symbol: str, source_name: str) -> str:
    lines = [
        f"/* Generated by gen_embed.py from {source_name} -- do not edit. */",
        "#include <stddef.h>",
        "",
        f"const char {symbol}[] = {{",
    ]
    if data:
        for i in range(0, len(data), BYTES_PER_LINE):
            chunk = data[i : i + BYTES_PER_LINE]
            lines.append("    " + ", ".join(format_byte(b) for b in chunk) + ",")
    lines.append("    0")
    lines.append("};")
    lines.append("")
    lines.append(f"const size_t {symbol}_len = {len(data)};")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(
            "usage: gen_embed.py input.lua output.c symbol_prefix",
            file=sys.stderr,
        )
        return 2

    src, dst, symbol = argv[1], argv[2], argv[3]
    with open(src, "rb") as fh:
        data = fh.read()

    out_dir = os.path.dirname(os.path.abspath(dst))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    text = generate(data, symbol, os.path.basename(src))
    with open(dst, "w", encoding="ascii", newline="\n") as fh:
        fh.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
