# Build static liblua + lua (and luac when present) from an official-style
# source tree (src/*.c). Upstream tarballs have no CMakeLists.txt.

function(lua_build_from_source ROOT)
    if(TARGET liblua)
        message(FATAL_ERROR "liblua already exists; cannot build another Lua from ${ROOT}")
    endif()

    set(_src "${ROOT}/src")
    if(NOT EXISTS "${_src}/lapi.c")
        if(EXISTS "${ROOT}/lapi.c")
            set(_src "${ROOT}")
        else()
            message(FATAL_ERROR "Lua sources not found under ${ROOT} (expected src/lapi.c)")
        endif()
    endif()

    file(GLOB _all_c "${_src}/*.c")
    set(_lib_srcs)
    foreach(_f IN LISTS _all_c)
        get_filename_component(_name "${_f}" NAME)
        if(_name STREQUAL "lua.c" OR _name STREQUAL "luac.c" OR _name STREQUAL "print.c")
            # interpreters / 5.1 luac helper — not part of liblua
        else()
            list(APPEND _lib_srcs "${_f}")
        endif()
    endforeach()
    if(NOT _lib_srcs)
        message(FATAL_ERROR "No Lua library sources in ${_src}")
    endif()

    add_library(liblua STATIC ${_lib_srcs})
    set_property(TARGET liblua PROPERTY FOLDER "lua")
    set_property(TARGET liblua PROPERTY POSITION_INDEPENDENT_CODE ON)

    set(_inc "")
    if(EXISTS "${ROOT}/inc/lua.h")
        set(_inc "${ROOT}/inc")
        target_include_directories(liblua PUBLIC "${ROOT}/inc")
    endif()
    if(EXISTS "${_src}/lua.h")
        if(NOT _inc)
            set(_inc "${_src}")
        endif()
        target_include_directories(liblua PUBLIC "${_src}")
    endif()
    if(NOT _inc)
        message(FATAL_ERROR "lua.h not found under ${ROOT}")
    endif()

    if(LUA_VERSION STREQUAL "5.2")
        target_compile_definitions(liblua PUBLIC LUA_COMPAT_ALL)
    elseif(LUA_VERSION STREQUAL "5.3")
        target_compile_definitions(liblua PUBLIC LUA_COMPAT_5_2)
    endif()

    if(WIN32)
        # Official Windows static build uses no LUA_USE_* define.
        target_compile_definitions(liblua PRIVATE _CRT_SECURE_NO_WARNINGS)
    elseif(APPLE)
        if(LUA_VERSION STREQUAL "5.1")
            target_compile_definitions(liblua PUBLIC LUA_USE_LINUX)
        else()
            target_compile_definitions(liblua PUBLIC LUA_USE_MACOSX)
        endif()
        target_link_libraries(liblua PUBLIC m)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_compile_definitions(liblua PUBLIC LUA_USE_LINUX)
        target_link_libraries(liblua PUBLIC m dl)
    else()
        target_compile_definitions(liblua PUBLIC LUA_USE_POSIX)
        target_link_libraries(liblua PUBLIC m)
    endif()

    add_executable(lua "${_src}/lua.c")
    target_link_libraries(lua PRIVATE liblua)
    set_property(TARGET lua PROPERTY FOLDER "lua")
    if(WIN32)
        target_compile_definitions(lua PRIVATE _CRT_SECURE_NO_WARNINGS)
    endif()

    if(EXISTS "${_src}/luac.c")
        set(_luac_srcs "${_src}/luac.c")
        if(EXISTS "${_src}/print.c")
            list(APPEND _luac_srcs "${_src}/print.c")
        endif()
        add_executable(luac ${_luac_srcs})
        target_link_libraries(luac PRIVATE liblua)
        set_property(TARGET luac PROPERTY FOLDER "lua")
        if(WIN32)
            target_compile_definitions(luac PRIVATE _CRT_SECURE_NO_WARNINGS)
        endif()
    endif()

    set(LUA_INCLUDE_DIR "${_inc}" PARENT_SCOPE)
endfunction()
